allow-newer: true
resolver: lts-18.14
compiler: ghc-8.10.7
packages:
  - .
extra-deps:
  - git: https://github.com/ucsd-progsys/liquidhaskell
    commit: 1ec324a075140382e13794fe8984f236de4efab4
    subdirs:
      - .
      - liquid-base
      - liquid-containers
      - liquid-prelude
      - liquid-ghc-prim
  - git: https://github.com/ucsd-progsys/liquid-fixpoint
    commit: 2b291c69544897420bc4372f1d4c18dcc2167658
  - rest-rewrite-0.1.1@sha256:7e180d3feb7185e41e3813e4d5a7aa8dfc1cfb479e754e22e706bcc99a26cf35,4793

